### ISSUE TITLE
Optimize Google Cloud Logging to lower costs

### ISSUE THREAD

**Issue by auto-mausx** [sig-net/mpc#60]
Our Dev environment is costing us the most amount of money, mostly in the form of logging. I would like to reduce this number by about half the current amount by adding exclusion filters on logs and reducing the sampling rate if possible. 

November Dev Environment Log cost:
1,422.10 CHF ~ $1617.13 USD

Current Actions taken:
- Filtered out noisy logs from services that don't provide much value (i.e. "received a new message")

**Comment by auto-mausx** [comment]
Pre filter log usage:
![Image](https://github.com/user-attachments/assets/490e9fa1-513a-437b-956f-bc25af5c847a)

This usage is more than 100,000 log entries every 30 seconds, which culminated to 3.5TB of log data in ~25 days in November.

Post filter log usage:
![Image](https://github.com/user-attachments/assets/e11f2b08-204f-4a42-8325-f099cffbc888)

I have reduced the usage to ~17,000 log entries per 30 seconds, we will see how that effects our bill over the next week or so and decide if further actions must be taken to reduce logging costs.

**Comment by ppca** [comment]
Nice savings! Look forward to the $ numbers to roll in

**Comment by volovyks** [comment]
Do we want to filter them out or remove them from our codebase? If you give us a chart of the most spammy logs, we can think about what can be removed.

**Comment by auto-mausx** [comment]
Feel free to keep them if they are useful, I just don't want to waste money ingesting them into Google. The filtered logs still exist on the machine/container, they just aren't being included with the Google logging agent pull, thus not adding cost to our bill.

**Comment by auto-mausx** [comment]
Here is the difference over the last few days when it comes to logging. I implemented this change on Dec 6th and it immediately cut our Logging usage to less than half, and our overall bill about half:
![Image](https://github.com/user-attachments/assets/246cbe58-6a1d-4471-bd0b-7ac9bb85e22d)

Next big user is networking (Dark orange color), however that is going to be pretty static, as Google's main cloud feature is its networking capabilities. Next beyond that we can control is CloudRun (lighter orange), most of which I would imagine is the grafana agents since they run 24/7. Once we get rid of MPC recovery, we should be able to  cut that cost slightly since those also run all the time.

**Comment by ppca** [comment]
wow at least 50 dollars saving per day. Nice!!

**Comment by auto-mausx** [comment]
I think we are in a pretty good spot with logging. This is about as close as we can get without sampling logs for the DEV environment. I will continue to monitor what we have and look for more opportunities  to cut some costs.
